/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.Component;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import resources.DateManager;

/**
 *
 * @author rodrigo
 */
public class PanelCompletarDatosDeTraslado extends javax.swing.JPanel {

    /**
     * Creates new form PanelCompletarDatosDeTraslado2
     */
    public PanelCompletarDatosDeTraslado() {
        initComponents();
        initTable();
    }
    
    public void initTable(){
        String[] columnas = new String[]{
            "N° comprobante", 
            "Proveedor", 
            "Importe", 
            "Salida Desde", 
            "Salida Fecha y Hora", 
            "Regreso Desde", 
            "Regreso Fecha y hora", 
            "Observaciones"
        };
        final Class[] tiposColumnas = new Class[]{
            java.lang.String.class, 
            java.lang.String.class, 
            java.lang.Double.class, 
            java.lang.String.class, 
            //com.toedter.calendar.JDateChooser.class, 
            DateManager.class,
            java.lang.String.class, 
            //com.toedter.calendar.JDateChooser.class, 
            DateManager.class,
            java.lang.String.class
        };
        
        Object[][] datos = new Object [][] {
            };
        
        this.tblDatosTraslado.setModel(new javax.swing.table.DefaultTableModel
            (datos,columnas){
                Class[] tipos = tiposColumnas;
                @Override
                public Class getColumnClass(int columnIndex) {
                    // Este método es invocado por el CellRenderer para saber que dibujar en la celda,
                    // observen que estamos retornando la clase que definimos de antemano.
                    return tipos[columnIndex];
                }
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Sobrescribimos este método para evitar que la columna que contiene los botones sea editada.
                    return true;
                }
            }
        );
        
        this.tblDatosTraslado.setDefaultRenderer(JDateChooser.class, 
                new TableCellRenderer(){
                    @Override
                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        return (Component) value;
                    }
                }
        );
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosTraslado = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnAgregarDatosAlojamientoComida = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlDatosAlojamientoComida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarFila = new javax.swing.JButton();
        btnEliminarFila = new javax.swing.JButton();

        tblDatosTraslado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° comprobante", "Proveedor", "Importe", "Salida Desde", "Salida Fecha y Hora", "Regreso Desde", "Regreso Fecha y hora", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatosTraslado);
        if (tblDatosTraslado.getColumnModel().getColumnCount() > 0) {
            tblDatosTraslado.getColumnModel().getColumn(5).setCellEditor(null);
            tblDatosTraslado.getColumnModel().getColumn(6).setCellEditor(null);
        }

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnAgregarDatosAlojamientoComida.setText("Agregar datos de alojamiento o comida");
        btnAgregarDatosAlojamientoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDatosAlojamientoComidaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        pnlDatosAlojamientoComida.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Completar datos de traslado");

        btnAgregarFila.setText("Agregar fila");
        btnAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaActionPerformed(evt);
            }
        });

        btnEliminarFila.setText("Eliminar fila seleccionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1)
                        .addGap(0, 236, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatosAlojamientoComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarFila)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarDatosAlojamientoComida)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosAlojamientoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAceptar)
                        .addComponent(btnCancelar)
                        .addComponent(btnAgregarDatosAlojamientoComida))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarFila)
                            .addComponent(btnEliminarFila))
                        .addGap(47, 47, 47)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAgregarDatosAlojamientoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDatosAlojamientoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDatosAlojamientoComidaActionPerformed

    private void btnAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarFilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnAgregarDatosAlojamientoComida;
    public javax.swing.JButton btnAgregarFila;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminarFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pnlDatosAlojamientoComida;
    public javax.swing.JTable tblDatosTraslado;
    // End of variables declaration//GEN-END:variables
}
