/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanastesis.view;

/**
 *
 * @author rodrigo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    PanelAdministrarRegistroUnico AdministrarRegistroUnico;
    PanelCompletarDatosDeAlojamientoOComida CompletarDatosDeAlojamientoOComida;
    PanelCompletarDatosDeDocentes CompletarDatosDeDocentes;
    PanelCompletarDatosDeTrasalado CompletarDatosDeTrasalado;
    PanelConfirmarLoteDeSolicitudesProcesadas ConfirmarLoteDeSolicitudesProcesadas;
    PanelCrearRegistroUnico CrearRegistroUnico;
    PanelIniciarSolicitud IniciarSolicitud;
    PanelListarSolicitudesProcesadas ListarSolicitudesProcesadas;
    PanelSolicitudesACompletarOGAGTD SolicitudesACompletarOGAGTD;
    
    public VentanaPrincipal() {
        initComponents();
        setPanelSolicitudesACompletarOGAGTD();
    }
    
    public void setPanelAdministrarRegistroUnico(){
        AdministrarRegistroUnico = new PanelAdministrarRegistroUnico();
        AdministrarRegistroUnico.setVisible(true);
        jScrollPane1.setViewportView(AdministrarRegistroUnico);
    }
    
    public void setPanelCompletarDatosDeAlojamientoOComida(){
        CompletarDatosDeAlojamientoOComida = new PanelCompletarDatosDeAlojamientoOComida();
        CompletarDatosDeAlojamientoOComida.setVisible(true);
        jScrollPane1.setViewportView(CompletarDatosDeAlojamientoOComida);
    }
    
    public void setPanelCompletarDatosDeDocentes(){
        CompletarDatosDeDocentes = new PanelCompletarDatosDeDocentes();
        CompletarDatosDeDocentes.setVisible(true);
        jScrollPane1.setViewportView(CompletarDatosDeDocentes);
    }
    
    public void setCompletarDatosDeTrasalado(){
        CompletarDatosDeTrasalado = new PanelCompletarDatosDeTrasalado();
        CompletarDatosDeTrasalado.setVisible(true);
        jScrollPane1.setViewportView(CompletarDatosDeTrasalado);
    }
    
    public void setPanelConfirmarLoteDeSolicitudesProcesadas(){
        ConfirmarLoteDeSolicitudesProcesadas = new PanelConfirmarLoteDeSolicitudesProcesadas();
        ConfirmarLoteDeSolicitudesProcesadas.setVisible(true);
        jScrollPane1.setViewportView(ConfirmarLoteDeSolicitudesProcesadas);
    }
    
    public void setPanelCrearRegistroUnico(){
        CrearRegistroUnico = new PanelCrearRegistroUnico();
        CrearRegistroUnico.setVisible(true);
        jScrollPane1.setViewportView(CrearRegistroUnico);
    }
    
     public void setPanelIniciarSolicitud(){
        IniciarSolicitud = new PanelIniciarSolicitud();
        IniciarSolicitud.setVisible(true);
        jScrollPane1.setViewportView(IniciarSolicitud);
    }
   
    public void setPanelListarSolicitudesProcesadas(){
        ListarSolicitudesProcesadas = new PanelListarSolicitudesProcesadas();
        ListarSolicitudesProcesadas.setVisible(true);
        jScrollPane1.setViewportView(ListarSolicitudesProcesadas);
    }
    
    public void setPanelSolicitudesACompletarOGAGTD(){
        SolicitudesACompletarOGAGTD = new PanelSolicitudesACompletarOGAGTD();
        SolicitudesACompletarOGAGTD.setVisible(true);
        jScrollPane1.setViewportView(SolicitudesACompletarOGAGTD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mItemIniciarNuevaSolicitud = new javax.swing.JMenuItem();
        mItemSolicitudesACompletar = new javax.swing.JMenuItem();
        mItemConfirmarLoteDeSolicitudesProcesadas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mItemListarHistorialDeSolicitudesProcesadas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Solicitudes");

        mItemIniciarNuevaSolicitud.setText("Iniciar nueva solicitud");
        mItemIniciarNuevaSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemIniciarNuevaSolicitudActionPerformed(evt);
            }
        });
        jMenu2.add(mItemIniciarNuevaSolicitud);

        mItemSolicitudesACompletar.setText("Solicitudes a completar");
        mItemSolicitudesACompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSolicitudesACompletarActionPerformed(evt);
            }
        });
        jMenu2.add(mItemSolicitudesACompletar);

        jMenuBar1.add(jMenu2);

        mItemConfirmarLoteDeSolicitudesProcesadas.setText("Administración");

        jMenuItem2.setText("Confirmar lote de solicitudes procesadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mItemConfirmarLoteDeSolicitudesProcesadas.add(jMenuItem2);

        mItemListarHistorialDeSolicitudesProcesadas.setText("Listar historlal de solicitudes procesadas");
        mItemListarHistorialDeSolicitudesProcesadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemListarHistorialDeSolicitudesProcesadasActionPerformed(evt);
            }
        });
        mItemConfirmarLoteDeSolicitudesProcesadas.add(mItemListarHistorialDeSolicitudesProcesadas);

        jMenuBar1.add(mItemConfirmarLoteDeSolicitudesProcesadas);

        jMenu3.setText("Usuario");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Pruba");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemListarHistorialDeSolicitudesProcesadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemListarHistorialDeSolicitudesProcesadasActionPerformed
        setPanelListarSolicitudesProcesadas();
    }//GEN-LAST:event_mItemListarHistorialDeSolicitudesProcesadasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mItemIniciarNuevaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemIniciarNuevaSolicitudActionPerformed
        setPanelIniciarSolicitud();
    }//GEN-LAST:event_mItemIniciarNuevaSolicitudActionPerformed

    private void mItemSolicitudesACompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSolicitudesACompletarActionPerformed
        setPanelSolicitudesACompletarOGAGTD();
    }//GEN-LAST:event_mItemSolicitudesACompletarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setPanelConfirmarLoteDeSolicitudesProcesadas();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mItemConfirmarLoteDeSolicitudesProcesadas;
    private javax.swing.JMenuItem mItemIniciarNuevaSolicitud;
    private javax.swing.JMenuItem mItemListarHistorialDeSolicitudesProcesadas;
    private javax.swing.JMenuItem mItemSolicitudesACompletar;
    // End of variables declaration//GEN-END:variables
}
